application: wise-logic-91506
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /assets
  static_dir: assets

- url: /javascripts
  static_dir: javascripts

- url: /admin/.*
  script: admin.application

- url: /.*
  script: submit.application


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest